# Generated by Django 4.2.27 on 2025-12-21 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название подразделения', max_length=100, verbose_name='Название')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Родительское подразделение в иерархии', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='staff.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, help_text='Полное имя сотрудника, например', max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(help_text='Должность сотрудника', max_length=100, verbose_name='Должность')),
                ('hire_date', models.DateField(help_text='Дата приёма на работу', verbose_name='Дата приёма')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Ежемесячная зарплата сотрудника. Должна быть неотрицательной', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата')),
                ('department', models.ForeignKey(help_text='Подразделение, в котором работает сотрудник', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='staff.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('full_name', 'department'), name='unique_employee_per_department'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_department_name_per_parent'),
        ),
    ]
